### ISSUE TITLE
Adopt https://github.com/drupal8-rector/drupal8-rector

### ISSUE THREAD

**Issue by andypost** [skilld-labs/skilld-docker-container#170]
The tool as evaluation of dgo.to/drupalmoduleupgrader 

Allows to convert deprecated code with yml-rules

Refs
* https://pronovix.com/blog/drupal-9-automated-deprecated-code-removal-proof-concept
* https://github.com/drupal8-rector/drupal8-rector
  * https://github.com/drupal8-rector/drupal8-rector/blob/master/config/drupal86-deprecations.yml
  * https://github.com/drupal8-rector/drupal8-rector/blob/master/config/drupal87-deprecations.yml

**Comment by andypost** [comment]
```
composer remove phpunit/phpunit
composer require drupal8-rector/drupal8-rector
```

```yml
imports:
  - { resource: "%vendor_dir%/drupal8-rector/drupal8-rector/config/drupal8.yml" }
  - { resource: "%vendor_dir%/drupal8-rector/drupal8-rector/config/drupal86-deprecations.yml" }
  - { resource: "%vendor_dir%/drupal8-rector/drupal8-rector/config/drupal87-deprecations.yml" }
  # Import drupal8-php71.yml ruleset if your module's minimum requirement
  # is PHP >= 7.1.
  - { resource: "%vendor_dir%/drupal8-rector/drupal8-rector/config/drupal8-php71.yml" }
  # Enable EXPERIMENTAL rectors.
  - { resource: "%vendor_dir%/drupal8-rector/drupal8-rector/config/drupal8-experimental.yml" }

parameters:
  autoload_paths:
    - 'core/modules'
    - 'modules'
    - 'modules/contrib'
    - 'modules/contrib/metatag'
    - 'core/profiles/demo_umami/modules/demo_umami_content'
  exclude_paths:
    - '*/tests/*'
    - '*/Tests/*'

services:
    # Optionally enable ReturnTypeDeclarationRector rector if your
    # code is PHP >= 7.1 compatible. It is disabled by default
    # because it may cause problems.
    # Drupal8Rector\Rector\FunctionLike\ReturnTypeDeclarationRectorProxy: ~
```

```
vendor/bin/rector process modules/contrib/metatag --dry-run
```
